# Generated by Django 3.2.4 on 2021-06-09 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 9, 16, 41, 48, 518432)),
        ),
    ]
