# Generated by Django 3.2.4 on 2021-06-09 16:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_bucket_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
