# Generated by Django 3.2.4 on 2021-06-16 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeapp', '0006_alter_bucket_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bucket', to=settings.AUTH_USER_MODEL),
        ),
    ]
