# Generated by Django 3.2.4 on 2021-06-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0008_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='heading',
            field=models.CharField(default='Article', max_length=225),
        ),
    ]
