# Generated by Django 3.2.4 on 2021-06-26 12:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0010_alter_article_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='theory',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
