# Generated by Django 3.2 on 2021-05-26 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logsys', '0008_alter_userprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
