# Generated by Django 3.2 on 2021-05-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsys', '0011_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='habit',
        ),
        migrations.AddField(
            model_name='profile',
            name='achievement',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='skill',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
