# Generated by Django 3.2 on 2021-06-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsys', '0012_auto_20210526_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='talent',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
