# Generated by Django 3.2.4 on 2021-06-09 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logsys', '0013_profile_talent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='skill',
            new_name='interest',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='achievement',
            new_name='want',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='talent',
        ),
    ]
