# Generated by Django 3.2.4 on 2021-06-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsys', '0015_reputation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rep',
            field=models.IntegerField(default=10),
        ),
        migrations.DeleteModel(
            name='Reputation',
        ),
    ]
